"""Initial migration

Revision ID: 31af46472d65
Revises: 
Create Date: 2026-02-14 17:13:52.203067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31af46472d65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssetType',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    if_not_exists=True
    )
    op.create_table('Asset',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2056), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['AssetType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Asset')
    op.drop_table('user')
    op.drop_table('AssetType')
    # ### end Alembic commands ###
