"""Remove unnecessary description column

Revision ID: 1808dd7dbb22
Revises: 0393664604ac
Create Date: 2026-02-15 15:25:58.156169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1808dd7dbb22'
down_revision: Union[str, Sequence[str], None] = '0393664604ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssetType', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssetType', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=2048), nullable=True))

    # ### end Alembic commands ###
