"""Added description for AssetType

Revision ID: 0393664604ac
Revises: 31af46472d65
Create Date: 2026-02-14 18:45:33.460081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0393664604ac'
down_revision: Union[str, Sequence[str], None] = '31af46472d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssetType', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssetType', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
